CREATE TABLE usuarios(
	ID_USUARIO SERIAL PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	LOGIN VARCHAR(50) NOT NULL UNIQUE,
	SENHA VARCHAR(100) NOT NULL,
	TIPO VARCHAR(20) NOT NULL CHECK (TIPO IN ('ADMIN', 'CLIENTE'))
);

CREATE TABLE endereco_cliente(
	ID_ENDERECO SERIAL PRIMARY KEY,
	RUA VARCHAR(100) NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	DESCRICAO VARCHAR(200) NOT NULL,
    BAIRRO VARCHAR(50) NOT NULL,
    CIDADE VARCHAR(50) NOT NULL
);

CREATE TABLE telefone_cliente(
	ID_TELEFONE SERIAL PRIMARY KEY,
	TELEFONE VARCHAR(15) NOT NULL UNIQUE,
    TIPO VARCHAR(20) NOT NULL CHECK (TIPO IN ('RESIDENCIAL', 'COMERCIAL', 'CELULAR'))
);

CREATE TABLE cliente(
	ID_CLIENTE SERIAL PRIMARY KEY,
	EMAIL VARCHAR(100) NOT NULL UNIQUE,
	CPF VARCHAR(11) NOT NULL UNIQUE,
	ID_USUARIO INT,
	ID_TELEFONE INT NULL,
    ID_ENDERECO INT NULL,
	FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
	FOREIGN KEY (ID_TELEFONE) REFERENCES TELEFONE_CLIENTE(ID_TELEFONE),
    FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO_CLIENTE(ID_ENDERECO)
);

CREATE TABLE carro (
    ID_CARRO SERIAL PRIMARY KEY,
    MODELO VARCHAR(50) NOT NULL,
    ANO INT NOT NULL CHECK (ANO > 1900 AND ANO <= EXTRACT(YEAR FROM CURRENT_DATE)),
    COR VARCHAR(20) NOT NULL,
    PLACA VARCHAR(10) NOT NULL UNIQUE,
    PRECO_DIARIA DECIMAL(10, 2) NOT NULL CHECK (PRECO_DIARIA > 0),
    DISPONIBILIDADE BOOLEAN NOT NULL DEFAULT TRUE CHECK (DISPONIBILIDADE IN (TRUE, FALSE))
);

CREATE TABLE carro_imagem (
    ID_IMAGEM SERIAL PRIMARY KEY,
    ID_CARRO INT NOT NULL,
    URL_IMAGEM VARCHAR(255) NOT NULL CHECK (LENGTH(URL_IMAGEM) > 0),
    ORDEM INT DEFAULT 1,
    FOREIGN KEY (ID_CARRO) REFERENCES carro(ID_CARRO)
);



CREATE TABLE carro_alugado (
    ID_CARRO_ALUGADO SERIAL PRIMARY KEY,
    ID_CARRO INT NOT NULL,
    ID_CLIENTE INT NOT NULL,
    DATA_ALUGUEL DATE NOT NULL,
    DATA_DEVOLUCAO DATE,
    FOREIGN KEY (ID_CARRO) REFERENCES carro(ID_CARRO),
    FOREIGN KEY (ID_CLIENTE) REFERENCES cliente(ID_CLIENTE)
);

